# Generated by Django 3.1.6 on 2021-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Message', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Queries',
        ),
    ]
