# Generated by Django 3.1.6 on 2021-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapaapp', '0002_auto_20211102_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Active', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='Products')),
                ('Product_Name', models.CharField(max_length=80)),
                ('Minimum_Quantity', models.CharField(blank=True, max_length=5000, null=True)),
                ('Price', models.CharField(blank=True, max_length=5000, null=True)),
                ('Price_Range', models.CharField(blank=True, max_length=5000, null=True)),
                ('Features', models.TextField(blank=True, max_length=5000, null=True)),
                ('Instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
